"""Generate the per-tutor documents from the framework YAML (1.1.91).

Two audiences, one source:

  docs/design/aipla/tutors/<id>.md            internal — researchers + engineers
  frontend/content/project/tutors/<id>.md     public — /project/tutors/<id>
  frontend/content/project/tutors.md          public hub — all frameworks

**Why generated rather than written.** A tutor's pedagogy already has a source of
truth: ``backend/frameworks/*.yaml``, whose behaviours are traceable to the
published literature. A hand-written companion doc is a second copy of that, and
a second copy drifts — silently, and in the direction of whichever one somebody
last edited. Generating both documents means the public page, the internal
record and the prompt the tutor actually receives cannot disagree.

``--check`` re-renders and fails if anything differs, so the drift is a red build
rather than a discovery months later. That is the same shape as the other guards
in ``scripts/``.

Run: ``make tutor-docs`` (write) · ``make check-tutor-docs`` (verify).
"""

from __future__ import annotations

import argparse
import datetime as _dt
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from db.models.teaching_framework import TeachingFramework
from frameworks.instruction import build_framework_instruction
from frameworks.loader import load_frameworks

_ROOT = Path(__file__).resolve().parents[2]
_DESIGN_DIR = _ROOT / "docs" / "design" / "aipla" / "tutors"
_PUBLIC_DIR = _ROOT / "frontend" / "content" / "project" / "tutors"
_PUBLIC_HUB = _ROOT / "frontend" / "content" / "project" / "tutors.md"

_BANNER = "<!-- GENERATED by backend/scripts/generate_tutor_docs.py from backend/frameworks/{id}.yaml — DO NOT EDIT BY HAND. Edit the YAML and run `make tutor-docs`. -->"

# Public pages carry a review deadline; keep it a round interval from the
# reviewed date so `check:project-content` has something real to enforce.
_REVIEW_MONTHS = 3

#: Sort position of the hub in /project; framework pages follow it.
_HUB_ORDER = 62

_DIMENSION_LABEL = {
    "epistemic": "Epistemic — how the student knows",
    "conceptual": "Conceptual — what the student knows",
}

_STATUS_PROSE = {
    "placeholder": (
        "**Not yet written.** The framework has a place in the library and a source, "
        "but its teaching moves have not been drafted. No tutor can be configured to use "
        "it, and it contributes nothing to any conversation."
    ),
    "ready_for_review": (
        "**Drafted, awaiting sign-off.** Every teaching move below is taken from the "
        "published source. The project's education researchers have still to review it."
    ),
    "ready": "**Reviewed and in use.** Signed off by the project's education researchers.",
}

_PUBLIC_STATUS = {"placeholder": "Provisional", "ready_for_review": "Provisional", "ready": "Current"}


def _reviewed_dates() -> tuple[str, str]:
    today = _dt.date.today()
    month = today.month + _REVIEW_MONTHS
    year = today.year + (month - 1) // 12
    return today.isoformat(), today.replace(year=year, month=(month - 1) % 12 + 1).isoformat()


def _constructs_block(fw: TeachingFramework, *, heading: str = "###") -> list[str]:
    out: list[str] = []
    for c in fw.constructs:
        out.append(f"{heading} {c.name.replace('_', ' ').capitalize()}")
        if c.summary:
            out.append(" ".join(c.summary.split()))
        tagged = [b for b in c.behaviours if b.dimension]
        untagged = [b for b in c.behaviours if not b.dimension]
        if untagged:
            out += ["", "**What the tutor does:**", ""]
            out.extend(f"- {b.text}" for b in untagged)
        for dim in ("epistemic", "conceptual"):
            in_dim = [b for b in tagged if b.dimension == dim]
            if in_dim:
                out += ["", f"**{_DIMENSION_LABEL[dim]}:**", ""]
                out.extend(f"- {b.text}" for b in in_dim)
        if c.avoid:
            out += ["", "**What the tutor is told NOT to do:**", ""]
            out.extend(f"- {a}" for a in c.avoid)
        if c.evaluation_hint:
            out += ["", f"**How you would know it happened:** {' '.join(c.evaluation_hint.split())}"]
        out.append("")
    return out


def _provenance_block(fw: TeachingFramework) -> list[str]:
    out = ["| Source | Vouched by | Note |", "|---|---|---|"]
    for p in fw.provenance:
        cite = " ".join(p.citation.split())
        note = " ".join((p.note or "—").split())
        out.append(f"| {cite} | {p.vouched_by} | {note} |")
    return out


def render_design_doc(fw: TeachingFramework) -> str:
    instruction = build_framework_instruction(fw)
    lines = [
        _BANNER.format(id=fw.id),
        "",
        f"# Tutor framework: {fw.label}",
        "",
        f"**Framework id:** `{fw.id}` · **Layer:** `{fw.layer}` · **Status:** `{fw.status}`",
        f"**Source of truth:** [`backend/frameworks/{fw.id}.yaml`](../../../../backend/frameworks/{fw.id}.yaml)",
        f"**Public page:** [/project/tutors/{fw.id}](../../../../frontend/content/project/tutors/{fw.id}.md)"
        if not fw.is_placeholder
        else "**Public page:** none — listed on the hub only, because it has no content to publish",
        "",
        _STATUS_PROSE[fw.status],
        "",
        "## What it is",
        "",
        " ".join((fw.summary or "").split()) or "_No summary yet._",
        "",
        "## Where it comes from",
        "",
        "Every teaching move below is traceable to these sources. A framework in AIPLA is",
        "structured data — constructs, observable behaviours, and the citation that backs",
        "them — precisely so that a reader can check the tutor's instruction against the",
        "theory instead of taking it on faith.",
        "",
        *_provenance_block(fw),
        "",
    ]

    if fw.constructs:
        lines += ["## The teaching moves", ""]
        lines += _constructs_block(fw)
        epi, con = fw.behaviours_in("epistemic"), fw.behaviours_in("conceptual")
        if epi or con:
            lines += [
                "### Inquiry dimensions",
                "",
                f"{len(epi)} behaviours are tagged **epistemic**, {len(con)} **conceptual**. "
                "Where a framework's source distinguishes the domains of scientific inquiry, "
                "the tag records which one a move belongs to — and it is applied only where "
                "that source applies it.",
                "",
            ]
    else:
        lines += [
            "## The teaching moves",
            "",
            "_None drafted._ The slot exists so the framework can be filled without a code",
            "change; until then it is inert by construction.",
            "",
        ]

    lines += [
        "## The instruction the tutor actually receives",
        "",
        "Rendered from the constructs above, verbatim — this is not a paraphrase of the",
        "prompt, it **is** the prompt. It is appended to the tutor's system instructions at",
        "the start of a conversation, and it is empty for a framework with no drafted moves.",
        "",
    ]
    if instruction:
        lines += ["```text", instruction, "```", ""]
    else:
        lines += ["_Empty — nothing is injected, and the tutor behaves exactly as it would with no framework._", ""]

    lines += [
        "## Who can change it, and how",
        "",
        "A researcher edits this framework's instruction at **`/teacher/research/frameworks`**",
        "in the running application — no commit, no deploy, no re-seed. The generated text",
        "above is always shown beside their edit, so a change reads as a delta from the",
        "theory rather than as an opaque prompt, and Revert restores it exactly.",
        "",
        "Edits are versioned and stamped with the researcher's verified identity. Structural",
        "changes — adding a construct, retagging a behaviour, correcting a citation — are made",
        f"in [`backend/frameworks/{fw.id}.yaml`](../../../../backend/frameworks/{fw.id}.yaml)",
        "and regenerate this document.",
        "",
        "## Related",
        "",
        "- [Researcher-configurable tutors (1.1.91)](../v1.1.0-feedback/researcher-configurable-tutors.md) — the design this framework layer implements",
        "- [Framework fit (1.1.107)](../v1.1.0-feedback/framework-fit-profile.md) — scoring how far a real conversation resembled this framework",
        "- [Session benchmark (1.1.92)](../v1.1.0-feedback/session-benchmark-tutor-activity.md) — comparing tutors against each other",
        "- [The literature corpus](../../../literature/tp-framework/README.md) — the papers themselves",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def render_public_page(fw: TeachingFramework, order: int) -> str:
    reviewed, review_by = _reviewed_dates()
    primary = " ".join(fw.provenance[0].citation.split()) if fw.provenance else ""
    lines = [
        "---",
        f'title: "{fw.label.replace(chr(34), "")}"',
        f'description: "How AIPLA\'s tutor teaches when configured to use {fw.label.split(chr(8212))[0].strip()}, and the research it is based on."',
        'eyebrow: "Teaching framework"',
        'owner: "AIPLA project team"',
        f'reviewed: "{reviewed}"',
        f'reviewBy: "{review_by}"',
        f'status: "{_PUBLIC_STATUS[fw.status]}"',
        f'order: "{order}"',
        'nav: "false"',
        "---",
        _BANNER.format(id=fw.id),
        "",
        f"# {fw.label}",
        "",
        " ".join((fw.summary or "").split()),
        "",
        "## Why this is published",
        "",
        "An AI tutor's teaching behaviour is usually invisible: it is a prompt inside a",
        "product, and nobody outside the team can see what the system was told to do. AIPLA",
        "publishes it. A teacher deciding whether to use this tutor, a student's parent, or a",
        "researcher reading our results can all read the instruction the tutor is working",
        "from and the study it comes from.",
        "",
        "## Where it comes from",
        "",
    ]
    if primary:
        lines += [f"This framework operationalises **{primary}**", ""]
    if len(fw.provenance) > 1:
        lines += ["It also draws on:", ""]
        lines += [f"- {' '.join(p.citation.split())}" for p in fw.provenance[1:]]
        lines += [""]
    lines += [
        "The moves below are the study's own coded strategies, not our summary of them. Where",
        "we could not verify something against the source, we say so rather than smoothing it",
        "over.",
        "",
        "## What the tutor does",
        "",
    ]
    lines += _constructs_block(fw)
    lines += [
        "## How it is reviewed",
        "",
        _STATUS_PROSE[fw.status],
        "",
        "The framework is held as structured data — each teaching move recorded separately,",
        "with the source that supports it — so that it can be checked line by line rather",
        "than read as a block of prose. The project's education researchers can revise the",
        "tutor's instruction directly in the application, and every revision is recorded",
        "against the person who made it.",
        "",
        "## Related",
        "",
        "- [All teaching frameworks](/project/tutors)",
        "- [How AIPLA is evaluated](/project/evaluation)",
        "- [Project decisions](/project/decisions)",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def render_hub(frameworks: list[TeachingFramework]) -> str:
    reviewed, review_by = _reviewed_dates()
    ready = [f for f in frameworks if not f.is_placeholder]
    lines = [
        "---",
        'title: "Teaching frameworks"',
        'description: "The research-based teaching approaches an AIPLA tutor can be configured to use, and the published studies behind each one."',
        'eyebrow: "How the tutors teach"',
        'owner: "AIPLA project team"',
        f'reviewed: "{reviewed}"',
        f'reviewBy: "{review_by}"',
        'status: "Provisional"',
        f'order: "{_HUB_ORDER}"',
        'nav: "true"',
        "---",
        "<!-- GENERATED by backend/scripts/generate_tutor_docs.py — DO NOT EDIT BY HAND. -->",
        "",
        "# Teaching frameworks",
        "",
        "An AIPLA tutor does not have a single fixed teaching style. It can be configured to",
        "follow a **teaching framework** — a documented approach from education research,",
        "describing what a teacher does turn by turn.",
        "",
        "Each framework is held as structured data rather than as a hidden prompt: the",
        "individual teaching moves, what the tutor is told to avoid, and the published study",
        "each comes from. That makes the tutor's behaviour reviewable by people who are not",
        "engineers — teachers, education researchers, and anyone assessing whether this is a",
        "reasonable thing to put in front of students.",
        "",
        "The library is being built out in collaboration with the University of Copenhagen's",
        "physics education researchers. Frameworks are listed here from the point they have a",
        "place in the library, including those whose content is still being written — showing",
        "an empty slot is more honest than showing nothing.",
        "",
        "| Framework | Status | Source |",
        "|---|---|---|",
    ]
    for fw in frameworks:
        name = f"[{fw.label}](/project/tutors/{fw.id})" if not fw.is_placeholder else fw.label
        state = {
            "placeholder": "Being written",
            "ready_for_review": "Drafted, in review",
            "ready": "In use",
        }[fw.status]
        src = " ".join(fw.provenance[0].citation.split()) if fw.provenance else "—"
        lines.append(f"| {name} | {state} | {src} |")
    lines += [
        "",
        f"**{len(ready)} of {len(frameworks)}** frameworks currently have their teaching moves written.",
        "",
        "## What a framework changes",
        "",
        "A tutor with no framework behaves as it always has. When a teacher or researcher",
        "assigns one, the framework's moves are added to the tutor's instructions for that",
        "activity — so the same underlying tutor can run a lesson as one approach or another,",
        "and the difference can be studied rather than assumed.",
        "",
        "## Related",
        "",
        "- [How AIPLA is evaluated](/project/evaluation)",
        "- [Project decisions](/project/decisions)",
        "- [Research](/project/research)",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if regeneration would change anything")
    args = ap.parse_args()

    frameworks = load_frameworks()
    planned: dict[Path, str] = {_PUBLIC_HUB: render_hub(frameworks)}
    # The hub sits at 62; each published framework takes the next slot in
    # catalogue order. `check:project-content` requires order to be unique
    # across the whole /project tree, so it cannot simply be a constant.
    order = _HUB_ORDER
    for fw in frameworks:
        planned[_DESIGN_DIR / f"{fw.id}.md"] = render_design_doc(fw)
        if not fw.is_placeholder:
            order += 1
            planned[_PUBLIC_DIR / f"{fw.id}.md"] = render_public_page(fw, order)

    stale = [p for p, body in planned.items() if not p.exists() or p.read_text(encoding="utf-8") != body]

    # A public page left behind by a framework that regressed to placeholder
    # would keep claiming content that no longer exists.
    orphans = [p for p in (_PUBLIC_DIR.glob("*.md") if _PUBLIC_DIR.exists() else []) if p not in planned] + [
        p for p in (_DESIGN_DIR.glob("*.md") if _DESIGN_DIR.exists() else []) if p not in planned
    ]

    if args.check:
        if not stale and not orphans:
            print(f"tutor-docs: OK ({len(planned)} documents match backend/frameworks/)")
            return 0
        for p in stale:
            print(f"  STALE  {p.relative_to(_ROOT)}")
        for p in orphans:
            print(f"  ORPHAN {p.relative_to(_ROOT)}")
        print("\ntutor-docs: out of date — run `make tutor-docs`")
        return 1

    _DESIGN_DIR.mkdir(parents=True, exist_ok=True)
    _PUBLIC_DIR.mkdir(parents=True, exist_ok=True)
    for p, body in planned.items():
        p.write_text(body, encoding="utf-8")
    for p in orphans:
        p.unlink()
    print(f"tutor-docs: wrote {len(planned)} document(s)" + (f", removed {len(orphans)} orphan(s)" if orphans else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
