"use client";

import { useEffect, useState } from "react";
import { BookOpen, RotateCcw, ShieldAlert } from "lucide-react";

import {
  type FrameworkStructure,
  type TeachingFrameworkPayload,
  listTeachingFrameworks,
  revertFrameworkInstruction,
  saveFrameworkStructure,
} from "@/lib/teacherApi";
import { EmptyState } from "@/components/teacher/ui/EmptyState";
import { TeacherCard } from "@/components/teacher/ui/TeacherCard";
import { TeacherPage } from "@/components/teacher/ui/TeacherPage";
import { FrameworkStructureEditor } from "@/components/teacher/research/FrameworkStructureEditor";
import { CustomApproachPanel } from "@/components/teacher/research/CustomApproachPanel";
import { TutorPreviewPanel } from "@/components/teacher/research/TutorPreviewPanel";
import { TutorCrossviewPanel } from "@/components/teacher/research/TutorCrossviewPanel";
import { TutorCopilot } from "./_TutorCopilot";
import type { TutorProposal } from "./tutorCopilotProposal";
import { TutorApproachPanel } from "@/components/teacher/research/TutorApproachPanel";

/** UI copy, lifted out of JSX (1.1.108 M4) so a translator can reach it.
 *
 *  The wording here is load-bearing rather than decorative. "Generated from the
 *  theory" was the badge until 2026-09-11 and told a reader nothing they could
 *  check: generated by what, from what, and can it invent? A researcher is being
 *  asked to trust that the tutor teaches what the paper says, so the page has to
 *  say plainly what the machine did and what it cannot do.
 */
const copy = {
  copilotApproachNote: (label: string) =>
    `The co-pilot proposed “${label}”. It is not saved — review the constructs and sources, then Save.`,
  copilotBehaviourNote: (name: string) =>
    `The co-pilot proposed behaviours for “${name}”. Add them to that construct below, then Save.`,
  teacherTierNote:
    "The seven published approaches are drawn from the research literature and are maintained by the research team, so they are not editable here. Your own approaches are — write one in your own words and assign it to a class like any other.",
  howItWorksTitle: "How a tutor gets its teaching approach",
  howItWorks: [
    "Each approach is a set of named constructs — the moves the framework is made of. Under each construct sit behaviours: single instructions quoted from the source paper's own coding scheme, and an avoid-list of the moves the paper codes as counter-indicative.",
    "Fixed code turns those constructs into the text the tutor is given, in one pass, with no AI involved. The behaviours are copied word for word — nothing is paraphrased, summarised or invented — so every line in the prompt can be traced back to a construct, and from there to a cited paper.",
    "That is what makes this reviewable: you can hold the prompt against the paper and check it. Editing the wording directly is allowed, and it breaks exactly that property, which is why the two buttons are labelled differently.",
  ],
  citationsTitle: "What the citations are for",
  citations:
    "Citations record where each construct came from and which person vouched for it. They are for you, not for the tutor — no citation is ever put in the tutor's prompt, and no student is shown one. A tutor that cited papers at a 16-year-old would be citing its own instructions. (Separately, the tutor DOES cite the classroom materials an activity gives it — that is a different mechanism.)",
  sourcesHeld:
    "The source PDFs are not in this app. They are private working copies of copyrighted papers, kept out of the repository; the citation is the durable record.",
  // Badges
  badgeUnedited: (n: number) => `Unedited · built from ${n} construct${n === 1 ? "" : "s"}`,
  badgeWordingEdited: "Wording hand-edited · no longer traceable to sources",
  badgeApproachEdited: "Approach edited · still traceable to sources",
  badgePlaceholder: "Awaiting pedagogical content",
  // Buttons
  editApproach: "Edit teaching approach",
  editWording: "Edit wording",
  close: "Close",
  // The mutual-exclusivity warning — the thing the UI never said
  exclusivityOnText:
    "Saving here REPLACES the generated text, and discards any edits made under “Edit teaching approach”. The tutor will then say exactly what you write, and the link back to the constructs and their sources is dropped. The two editors are alternatives, not layers — whichever you save last is the one that runs.",
  exclusivityOnStructure:
    "Saving here regenerates what the tutor is told from the constructs below, and discards any hand-written wording saved under “Edit wording”. The two editors are alternatives, not layers — whichever you save last is the one that runs.",
  liveNow: "Live now — this is what the tutor receives",
  generatedLabel: (n: number) =>
    `Assembled from ${n} construct${n === 1 ? "" : "s"} — the version without your edits`,
  whatTutorIsTold: "What the tutor is told",
  sourcesLabel: "Sources this approach is built from",
  vouchedBy: (who: string) => `vouched by ${who}`,
  revert: "Revert to generated",
  saving: "Saving…",
  save: "Save",
} as const;

type Status = "loading" | "ok" | "forbidden" | "error";

/** There is one editor (1.1.110).
 *
 *  A researcher used to be able to edit the RENDERED instruction directly, as
 *  an alternative to editing the constructs. It was removed: it was the only
 *  path in the system that could produce a tutor prompt no reader could check
 *  against a source, which is the property this whole layer exists to protect.
 *  Free-text authoring now lives on a CUSTOM approach, which declares that it
 *  was written rather than derived.
 *
 *  Kept as a type rather than deleted so the reopen-on-last-used logic still
 *  reads as a choice; a legacy `overrideMode: "text"` row simply opens here.
 */
type EditorMode = "structure";

/**
 * Teaching frameworks (1.1.91 M1) — researcher-only.
 *
 * The surface that makes the design doc's premise false in the right direction:
 * a tutor's pedagogy stops being a file in git that only a developer can edit.
 * A researcher reads the instruction generated from the framework's constructs,
 * edits it, and the next tutor turn uses the edit — no commit, no deploy, no
 * seed.
 *
 * The generated text is always shown beside the override rather than replaced
 * by it, so an edit reads as a *delta from the theory*. That is what keeps a
 * hand-written prompt reviewable, which is the whole reason the framework
 * carries structured constructs instead of a prompt string.
 *
 * Access is enforced by the backend (`assert_researcher` on every route), so a
 * non-researcher who reaches this URL gets an access-required state.
 */
export default function ResearchFrameworksPage() {
  const [status, setStatus] = useState<Status>("loading");
  const [frameworks, setFrameworks] = useState<TeachingFrameworkPayload[]>([]);
  const [openId, setOpenId] = useState<string | null>(null);
  const [mode, setMode] = useState<EditorMode>("structure");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  /** What the co-pilot last proposed and the researcher Applied. Held on the
   *  page, NOT written: Apply opens the editor on it, and the existing
   *  researcher-gated PUT .../structure stays the only path to a saved change,
   *  so the live preview a researcher signs off is what gets stored. */
  const [copilotNote, setCopilotNote] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    listTeachingFrameworks()
      .then((rows) => {
        if (cancelled) return;
        setFrameworks(rows);
        setStatus("ok");
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        const forbidden = err instanceof Error && err.message.includes(" 403");
        setStatus(forbidden ? "forbidden" : "error");
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const replace = (updated: TeachingFrameworkPayload) =>
    setFrameworks((rows) => rows.map((r) => (r.id === updated.id ? updated : r)));

  const open = (fw: TeachingFrameworkPayload) => {
    setOpenId(fw.id);
    setMode("structure");
    setError(null);
  };

  const saveStructure = async (fw: TeachingFrameworkPayload, structure: FrameworkStructure) => {
    setBusy(true);
    setError(null);
    try {
      replace(await saveFrameworkStructure(fw.id, structure));
      setOpenId(null);
    } catch {
      setError("Could not save. Your edit is still here — try again.");
    } finally {
      setBusy(false);
    }
  };

  const revert = async (fw: TeachingFrameworkPayload) => {
    setBusy(true);
    setError(null);
    try {
      const updated = await revertFrameworkInstruction(fw.id);
      replace(updated);
    } catch {
      setError("Could not revert. Try again.");
    } finally {
      setBusy(false);
    }
  };

  /** A proposal the researcher Applied. Opens the relevant editor and says what
   *  still has to happen — a proposal carries no citation, so it is never one
   *  click from being saved as though it did. */
  const onCopilotProposal = (proposal: TutorProposal) => {
    if (proposal.kind === "propose_approach") {
      setCopilotNote(copy.copilotApproachNote(proposal.label));
    } else {
      setCopilotNote(copy.copilotBehaviourNote(proposal.constructName));
    }
  };

  return (
    <TeacherPage
      title="Teaching frameworks"
      subtitle={
        status === "ok" ? `${frameworks.length} frameworks · what the tutor is told to do` : undefined
      }
    >
      {status === "loading" ? (
        <p className="text-sm text-muted-foreground">Loading frameworks&hellip;</p>
            ) : status === "forbidden" ? (
        /* Not a wall for a TEACHER (1.1.110). The published frameworks are
           researcher-maintained, so listing them 403s — but a teacher's own
           approaches are the one thing on this screen they DO own, and showing
           an access-required page would hide a surface built for them. */
        <div className="space-y-4">
          <p className="text-sm text-muted-foreground">{copy.teacherTierNote}</p>
          {/* The 09-09 ask — the tutor library as teacher training — lands
              here, for the audience it was requested for. */}
          <TutorPreviewPanel />
          <CustomApproachPanel />
        </div>
      ) : status === "error" ? (
        <EmptyState
          icon={ShieldAlert}
          title="Could not load frameworks"
          description="Something went wrong reading the framework catalogue. Reload to try again."
        />
      ) : (
        <div className="space-y-4">
          {/* The trust panel (2026-09-11). The page previously asserted that the
              prompt was "generated from the theory" and left the reader to guess
              what that meant — generated by what, and could it invent? A
              researcher is being asked to stake their name on this, so the
              mechanism is stated plainly and up front rather than implied by a
              badge. Collapsed by default so it does not shout at someone who
              already knows. */}
          <details className="rounded border border-border bg-muted/30 px-4 py-3">
            <summary className="cursor-pointer text-sm font-medium">{copy.howItWorksTitle}</summary>
            <div className="mt-3 space-y-3 text-sm text-muted-foreground">
              {copy.howItWorks.map((para, i) => (
                <p key={i}>{para}</p>
              ))}
              <div className="rounded border border-border bg-background px-3 py-2">
                <p className="text-xs font-medium text-foreground">{copy.citationsTitle}</p>
                <p className="mt-1 text-xs">{copy.citations}</p>
                <p className="mt-1 text-xs">{copy.sourcesHeld}</p>
              </div>
            </div>
          </details>
          <TutorApproachPanel
            frameworks={frameworks.map((f) => ({
              id: f.id,
              // The teacher-facing plain name lives on /api/tutors; here the
              // label is what we have, and a researcher knows the theory names.
              name: f.label,
              isPlaceholder: f.status === "placeholder",
            }))}
          />
          {copilotNote ? (
            <p
              role="status"
              className="rounded border border-brand/40 bg-brand/5 px-3 py-2 text-sm text-foreground"
            >
              {copilotNote}
            </p>
          ) : null}
          <TutorPreviewPanel />
          <CustomApproachPanel />
          {/* Researcher-only: a cross-tenancy read of every teacher's work
              (1.1.91 M4). The teacher tier above never renders it. */}
          <TutorCrossviewPanel />
          {frameworks.map((fw) => {
            const isOpen = openId === fw.id;
            const editable = fw.status !== "placeholder";
            return (
              <TeacherCard key={fw.id}>
                <div className="flex items-start justify-between gap-4">
                  <div className="min-w-0">
                    <h2 className="flex items-center gap-2 text-base font-medium">
                      <BookOpen className="h-4 w-4 shrink-0 text-muted-foreground" aria-hidden />
                      {fw.label}
                    </h2>
                    <p className="mt-1 text-sm text-muted-foreground">{fw.summary}</p>
                    <div className="mt-2 flex flex-wrap gap-2 text-xs">
                      {fw.status === "placeholder" ? (
                        <span className="rounded bg-muted px-2 py-0.5 text-muted-foreground">
                          {copy.badgePlaceholder}
                        </span>
                      ) : null}
                      {/* A placeholder has no constructs, so there is nothing
                          generated to claim — it gets neither badge.

                          The two override badges say different things on
                          purpose. A STRUCTURAL edit keeps the prompt derived
                          from cited constructs; a WORDING edit does not, and a
                          reader deciding whether to trust this framework needs
                          to see which of those happened without opening it. */}
                      {!editable ? null : fw.isOverridden ? (
                        <span className="rounded bg-brand/10 px-2 py-0.5 text-brand">
                          {fw.overrideMode === "text" ? copy.badgeWordingEdited : copy.badgeApproachEdited}
                          {fw.overrideVersion ? ` · v${fw.overrideVersion}` : ""}
                        </span>
                      ) : (
                        <span className="rounded bg-muted px-2 py-0.5 text-muted-foreground">
                          {copy.badgeUnedited(fw.constructs.length)}
                        </span>
                      )}
                    </div>
                  </div>
                  {editable ? (
                    <div className="flex shrink-0 gap-2">
                      <button
                        type="button"
                        onClick={() => (isOpen ? setOpenId(null) : open(fw))}
                        className="rounded border px-3 py-1.5 text-sm hover:bg-muted"
                      >
                        {isOpen && mode === "structure" ? copy.close : copy.editApproach}
                      </button>
                    </div>
                  ) : null}
                </div>

                {isOpen ? (
                  <FrameworkStructureEditor
                    framework={fw}
                    busy={busy}
                    error={error}
                    onCancel={() => setOpenId(null)}
                    onSave={(structure) => void saveStructure(fw, structure)}
                    /* Revert lived in the text editor, which is gone (1.1.110).
                       It has to stay reachable: "Reset to published" only
                       repopulates the form — the saved override survives until
                       this deletes it, and a researcher who could not find this
                       would think resetting had reverted when it had not. */
                    onRevert={fw.isOverridden ? () => void revert(fw) : undefined}
                  />
                ) : null}

              </TeacherCard>
            );
          })}
          {/* The fourth co-pilot mount (1.1.91 M2), on the surface it edits.
              Researcher-only twice over: the skill is tagged role:researcher
              AND every tool re-checks the claim server-side. */}
          <TutorCopilot onProposal={onCopilotProposal} />
        </div>
      )}
    </TeacherPage>
  );
}
