"use client";

import { useEffect, useState } from "react";
import { BookOpen, RotateCcw, ShieldAlert } from "lucide-react";

import {
  type FrameworkStructure,
  type TeachingFrameworkPayload,
  listTeachingFrameworks,
  revertFrameworkInstruction,
  saveFrameworkStructure,
} from "@/lib/teacherApi";
import { EmptyState } from "@/components/teacher/ui/EmptyState";
import { TeacherCard } from "@/components/teacher/ui/TeacherCard";
import { TeacherPage } from "@/components/teacher/ui/TeacherPage";
import { TeacherTabs } from "@/components/teacher/ui/TeacherTabs";
import { FrameworkStructureEditor } from "@/components/teacher/research/FrameworkStructureEditor";
import { CustomApproachPanel } from "@/components/teacher/research/CustomApproachPanel";
import { MyTutorsPanel } from "@/components/teacher/research/MyTutorsPanel";
import { PersonaEditorPanel } from "@/components/teacher/research/PersonaEditorPanel";
import { SourcePassagePanel } from "@/components/teacher/research/SourcePassagePanel";
import { PublishedApproachList } from "@/components/teacher/research/PublishedApproachList";
import { TutorPreviewPanel } from "@/components/teacher/research/TutorPreviewPanel";
import { TutorCrossviewPanel } from "@/components/teacher/research/TutorCrossviewPanel";
import { CalibrationSetPanel } from "@/components/teacher/research/CalibrationSetPanel";
import { TutorCopilot } from "./_TutorCopilot";
import type { TutorProposal } from "./tutorCopilotProposal";
import { TutorApproachPanel } from "@/components/teacher/research/TutorApproachPanel";
import { useT } from "@/i18n";

/** UI copy, lifted out of JSX (1.1.108 M4) so a translator can reach it.
 *
 *  The wording here is load-bearing rather than decorative. "Generated from the
 *  theory" was the badge until 2026-09-11 and told a reader nothing they could
 *  check: generated by what, from what, and can it invent? A researcher is being
 *  asked to trust that the tutor teaches what the paper says, so the page has to
 *  say plainly what the machine did and what it cannot do.
 */
// Copy lives in messages/*/teacher-research.json — 1.1.108.

type Status = "loading" | "ok" | "forbidden" | "error";

/** There is one editor (1.1.110).
 *
 *  A researcher used to be able to edit the RENDERED instruction directly, as
 *  an alternative to editing the constructs. It was removed: it was the only
 *  path in the system that could produce a tutor prompt no reader could check
 *  against a source, which is the property this whole layer exists to protect.
 *  Free-text authoring now lives on a CUSTOM approach, which declares that it
 *  was written rather than derived.
 *
 *  Kept as a type rather than deleted so the reopen-on-last-used logic still
 *  reads as a choice; a legacy `overrideMode: "text"` row simply opens here.
 */
type EditorMode = "structure";

/**
 * Teaching frameworks (1.1.91 M1) — researcher-only.
 *
 * The surface that makes the design doc's premise false in the right direction:
 * a tutor's pedagogy stops being a file in git that only a developer can edit.
 * A researcher reads the instruction generated from the framework's constructs,
 * edits it, and the next tutor turn uses the edit — no commit, no deploy, no
 * seed.
 *
 * The generated text is always shown beside the override rather than replaced
 * by it, so an edit reads as a *delta from the theory*. That is what keeps a
 * hand-written prompt reviewable, which is the whole reason the framework
 * carries structured constructs instead of a prompt string.
 *
 * Access is enforced by the backend (`assert_researcher` on every route), so a
 * non-researcher who reaches this URL gets an access-required state.
 */
export default function ResearchFrameworksPage() {
  const t = useT("ResearchFrameworksPage");
  const [status, setStatus] = useState<Status>("loading");
  const [frameworks, setFrameworks] = useState<TeachingFrameworkPayload[]>([]);
  const [openId, setOpenId] = useState<string | null>(null);
  const [mode, setMode] = useState<EditorMode>("structure");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  /** What the co-pilot last proposed and the researcher Applied. Held on the
   *  page, NOT written: Apply opens the editor on it, and the existing
   *  researcher-gated PUT .../structure stays the only path to a saved change,
   *  so the live preview a researcher signs off is what gets stored. */
  const [copilotNote, setCopilotNote] = useState<string | null>(null);
  /** Which tab is open. The page grew five panels and seven framework cards in
   *  one sprint and became a single scroll nobody could navigate; tabs give
   *  each job a place. Panels stay MOUNTED behind `hidden`, so a half-written
   *  approach survives a glance at another tab. */
  const [tab, setTab] = useState("approaches");
  /** Which of the published approaches the Approaches tab is showing. They used
   *  to be seven full cards stacked in one pane, so "which one am I editing?"
   *  took a scroll to answer; they are a rail and a detail pane now. */
  const [approachId, setApproachId] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    listTeachingFrameworks()
      .then((rows) => {
        if (cancelled) return;
        setFrameworks(rows);
        setStatus("ok");
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        const forbidden = err instanceof Error && err.message.includes(" 403");
        setStatus(forbidden ? "forbidden" : "error");
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const replace = (updated: TeachingFrameworkPayload) =>
    setFrameworks((rows) => rows.map((r) => (r.id === updated.id ? updated : r)));

  const open = (fw: TeachingFrameworkPayload) => {
    setOpenId(fw.id);
    setMode("structure");
    setError(null);
  };

  const saveStructure = async (fw: TeachingFrameworkPayload, structure: FrameworkStructure) => {
    setBusy(true);
    setError(null);
    try {
      replace(await saveFrameworkStructure(fw.id, structure));
      setOpenId(null);
    } catch {
      setError(t("saveFailed"));
    } finally {
      setBusy(false);
    }
  };

  const revert = async (fw: TeachingFrameworkPayload) => {
    setBusy(true);
    setError(null);
    try {
      const updated = await revertFrameworkInstruction(fw.id);
      replace(updated);
    } catch {
      setError(t("revertFailed"));
    } finally {
      setBusy(false);
    }
  };

  /** A proposal the researcher Applied. Opens the relevant editor and says what
   *  still has to happen — a proposal carries no citation, so it is never one
   *  click from being saved as though it did. */
  const onCopilotProposal = (proposal: TutorProposal) => {
    if (proposal.kind === "propose_approach") {
      setCopilotNote(t("copilotApproachNote", { label: proposal.label }));
    } else {
      setCopilotNote(t("copilotBehaviourNote", { name: proposal.constructName }));
    }
  };

  /** The rail's selection, but never a dangling one: a saved edit replaces the
   *  row, and a framework can leave the list entirely, so the id is validated
   *  against what actually loaded rather than trusted. */
  const activeApproach =
    frameworks.find((f) => f.id === approachId)?.id ?? frameworks[0]?.id ?? "";

  const approachCard = (fw: TeachingFrameworkPayload) => {
    const isOpen = openId === fw.id;
    const editable = fw.status !== "placeholder";
    return (
      <TeacherCard>
        <div className="flex items-start justify-between gap-4">
          <div className="min-w-0">
            <h2 className="flex items-center gap-2 text-base font-medium">
              <BookOpen className="h-4 w-4 shrink-0 text-muted-foreground" aria-hidden />
              {fw.label}
            </h2>
            <p className="mt-1 text-sm text-muted-foreground">{fw.summary}</p>
            <div className="mt-2 flex flex-wrap gap-2 text-xs">
              {fw.status === "placeholder" ? (
                <span className="rounded bg-muted px-2 py-0.5 text-muted-foreground">
                  {t("badgePlaceholder")}
                </span>
              ) : null}
              {/* A placeholder has no constructs, so there is nothing
                  generated to claim — it gets neither badge.

                  The two override badges say different things on
                  purpose. A STRUCTURAL edit keeps the prompt derived
                  from cited constructs; a WORDING edit does not, and a
                  reader deciding whether to trust this framework needs
                  to see which of those happened without opening it. */}
              {!editable ? null : fw.isOverridden ? (
                <span className="rounded bg-brand/10 px-2 py-0.5 text-brand">
                  {fw.overrideMode === "text" ? t("badgeWordingEdited") : t("badgeApproachEdited")}
                  {fw.overrideVersion ? ` · v${fw.overrideVersion}` : ""}
                </span>
              ) : (
                <span className="rounded bg-muted px-2 py-0.5 text-muted-foreground">
                  {t("badgeUnedited", { n: fw.constructs.length })}
                </span>
              )}
            </div>
          </div>
          {editable ? (
            <div className="flex shrink-0 gap-2">
              <button
                type="button"
                onClick={() => (isOpen ? setOpenId(null) : open(fw))}
                className="rounded border px-3 py-1.5 text-sm hover:bg-muted"
              >
                {isOpen && mode === "structure" ? t("close") : t("editApproach")}
              </button>
            </div>
          ) : null}
        </div>

        {isOpen ? (
          <FrameworkStructureEditor
            framework={fw}
            busy={busy}
            error={error}
            onCancel={() => setOpenId(null)}
            onSave={(structure) => void saveStructure(fw, structure)}
            /* Revert lived in the text editor, which is gone (1.1.110).
               It has to stay reachable: "Reset to published" only
               repopulates the form — the saved override survives until
               this deletes it, and a researcher who could not find this
               would think resetting had reverted when it had not. */
            onRevert={fw.isOverridden ? () => void revert(fw) : undefined}
          />
        ) : null}

        {/* The backend could do this from 1.1.110 and nothing called it, so
            "vouched by M" stayed a claim a reader had to take on trust — on the
            one screen whose whole argument is that a prompt can be held against
            its source. Researcher tier only; the passages are verbatim
            copyrighted extracts. */}
        {fw.status !== "placeholder" ? <SourcePassagePanel frameworkId={fw.id} /> : null}
      </TeacherCard>
    );
  };

  /** One rail entry per published approach. Cards stay MOUNTED behind `hidden`,
   *  so an open editor with unsaved changes survives a look at another
   *  approach — the same property the outer tabs have. */
  const approachesPanel = (
    <>
      {frameworks.length === 0 ? null : (
        <TeacherTabs
          ariaLabel={t("railLabel")}
          orientation="vertical"
          active={activeApproach}
          onChange={setApproachId}
          tabs={frameworks.map((fw) => ({
            id: fw.id,
            label: fw.label,
            hint:
              fw.status === "placeholder"
                ? t("railPlaceholder")
                : fw.isOverridden
                  ? t("railEdited")
                  : t("railConstructs", { n: fw.constructs.length }),
            content: approachCard(fw),
          }))}
        />
      )}
      <CustomApproachPanel />
    </>
  );

  return (
    <TeacherPage
      title={t("title")}
      subtitle={status === "ok" ? t("subtitle", { n: frameworks.length }) : undefined}
    >
      {status === "loading" ? (
        <p className="text-sm text-muted-foreground">{t("loading")}</p>
            ) : status === "forbidden" ? (
        /* Not a wall for a TEACHER (1.1.110). The published frameworks are
           researcher-maintained, so listing them 403s — but a teacher's own
           approaches are the one thing on this screen they DO own, and showing
           an access-required page would hide a surface built for them. */
        <div className="flex flex-col gap-4">
          <p className="text-sm text-muted-foreground">{t("teacherTierNote")}</p>
          <TeacherTabs
            ariaLabel={t("title")}
            active={tab === "approaches" ? "try" : tab}
            onChange={setTab}
            tabs={[
              // "Try them" leads for a teacher: the 09-09 ask was the tutor
              // library as teaching training, and that is the thing they came
              // for. Authoring is the second question, not the first.
              { id: "try", label: t("tabTry"), content: <TutorPreviewPanel /> },
              // TUTOR-2 M1 — READING the seven, which a teacher could not do at
              // all before. 1.1.135 requires a teacher building a tutor to pick
              // an approach somebody can read; an invisible one cannot be read.
              // It sits between trying and writing because that is the order of
              // the questions: what do these do, what are they made of, can I
              // write my own.
              { id: "published", label: t("tabApproaches"), content: <PublishedApproachList /> },
              { id: "yours", label: t("tabYours"), content: <CustomApproachPanel /> },
              // TUTOR-2 M2 — where a tutor is MADE. The home
              // TutorVariantDialog's own docstring asked for on 2026-09-11
              // when it was dropped from the class settings page: "a class is
              // where you CHOOSE a tutor; authoring a research instrument is a
              // different job done at a different moment".
              { id: "tutors", label: t("tabTutors"), content: <MyTutorsPanel /> },
              // TUTOR-2 M3/M4/M5 — the face and the voice. Beside the tutors
              // because they are the two halves of one answer to "make your
              // own tutor": the approach says how it teaches, the persona says
              // who is teaching.
              { id: "faces", label: t("tabFaces"), content: <PersonaEditorPanel /> },
            ]}
          />
        </div>
      ) : status === "error" ? (
        <EmptyState
          icon={ShieldAlert}
          title={t("errorTitle")}
          description={t("errorBody")}
        />
      ) : (
        <div className="flex flex-col gap-4">
          {/* The trust panel (2026-09-11). The page previously asserted that the
              prompt was "generated from the theory" and left the reader to guess
              what that meant. Stays ABOVE the tabs: it explains the mechanism
              every tab relies on, and burying it in one of them would make it
              findable only by someone who already knew. */}
          <details className="rounded border border-border bg-muted/30 px-4 py-3">
            <summary className="cursor-pointer text-sm font-medium">{t("howItWorksTitle")}</summary>
            <div className="mt-3 space-y-3 text-sm text-muted-foreground">
              {(["howItWorks1", "howItWorks2", "howItWorks3"] as const).map((key) => (
                <p key={key}>{t(key)}</p>
              ))}
              <div className="rounded border border-border bg-background px-3 py-2">
                <p className="text-xs font-medium text-foreground">{t("citationsTitle")}</p>
                <p className="mt-1 text-xs">{t("citations")}</p>
                <p className="mt-1 text-xs">{t("sourcesHeld")}</p>
              </div>
            </div>
          </details>

          {copilotNote ? (
            <p
              role="status"
              className="rounded border border-brand/40 bg-brand/5 px-3 py-2 text-sm text-foreground"
            >
              {copilotNote}
            </p>
          ) : null}

          <TeacherTabs
            ariaLabel={t("title")}
            active={tab}
            onChange={setTab}
            tabs={[
              {
                id: "approaches",
                label: t("tabApproaches"),
                count: frameworks.length,
                content: approachesPanel,
              },
              {
                id: "assign",
                label: t("tabAssign"),
                content: (
                  <TutorApproachPanel
                    frameworks={frameworks.map((f) => ({
                      id: f.id,
                      // The teacher-facing plain name lives on /api/tutors; here
                      // the label is what we have, and a researcher knows the
                      // theory names.
                      name: f.label,
                      isPlaceholder: f.status === "placeholder",
                    }))}
                  />
                ),
              },
              { id: "try", label: t("tabTry"), content: <TutorPreviewPanel /> },
              // TUTOR-2 M2 — the SAME authoring panel the teacher tier gets.
              // One surface, graded by role: `canEdit` is computed per row on
              // the server, so a researcher simply sees more rows as theirs to
              // act on rather than meeting a different component.
              { id: "tutors", label: t("tabTutors"), content: <MyTutorsPanel /> },
              { id: "faces", label: t("tabFaces"), content: <PersonaEditorPanel /> },
              // Researcher-only: a cross-tenancy read of every teacher's work
              // (1.1.91 M4). The teacher tier never renders it.
              { id: "usage", label: t("tabUsage"), content: <TutorCrossviewPanel /> },
              // Researcher-only: every researcher's corrections of the fidelity
              // judge as a calibration set + agreement (1.1.148, M 2026-10-08).
              { id: "calibration", label: t("tabCalibration"), content: <CalibrationSetPanel /> },
            ]}
          />
          {/* The fourth co-pilot mount (1.1.91 M2), on the surface it edits.
              Researcher-only twice over: the skill is tagged role:researcher
              AND every tool re-checks the claim server-side. */}
          <TutorCopilot onProposal={onCopilotProposal} />
        </div>
      )}
    </TeacherPage>
  );
}
