#!/usr/bin/env bash
# Regenerate the PWA / home-screen icon PNGs from the single SVG source.
#
# Why this script exists (2026-08-14): the first cut of the PWA icons was
# generated by hand from `aipla-mark.svg`, which has rounded corners — so the
# PNGs carried TRANSPARENT corners. iOS requires an opaque square for
# `apple-touch-icon` (it applies its own rounding); given transparency it
# composites against black or drops the icon entirely and uses a screenshot of
# the page. Result: "I added it to my home screen and there's no icon."
#
# `-b '#901a1e'` flattens the alpha channel against KU red, so the output is
# opaque even though rsvg-convert always emits RGBA. `scripts/check-pwa-icons.mjs`
# asserts that, because "looks fine on my laptop" is exactly how this shipped.
set -euo pipefail

cd "$(dirname "$0")/.."
SRC="frontend/public/images/logo/aipla-icon-src.svg"
OUT="frontend/public/images/logo"
BG="#901a1e" # KU red — must match --brand in globals.css and manifest theme_color

if ! command -v rsvg-convert >/dev/null 2>&1; then
  echo "FATAL: rsvg-convert not found. brew install librsvg" >&2
  exit 1
fi
[ -f "$SRC" ] || { echo "FATAL: missing $SRC" >&2; exit 1; }

gen() { # gen <size> <filename>
  rsvg-convert -w "$1" -h "$1" -b "$BG" "$SRC" -o "$OUT/$2"
  echo "  $2  ${1}x${1}"
}

echo "Regenerating PWA icons from $SRC (background $BG):"
gen 180 apple-touch-icon.png     # iOS home screen. Opaque + unrounded is mandatory.
gen 192 icon-192.png             # manifest, purpose "any"
gen 512 icon-512.png             # manifest, purpose "any"
gen 512 icon-maskable-512.png    # manifest, purpose "maskable" (Android crops it)

echo
echo "Done. Verify with: node scripts/check-pwa-icons.mjs"
echo "NOTE: iOS caches home-screen icons — remove and re-add the shortcut to see a change."
