#!/usr/bin/env bash
#
# port-up.sh — move platform improvements from this fork up to the template.
#
# The missing half of the loop. This repo has run for four months as a hard
# fork: every guard it wrote because a bug shipped once (check-auth-dispatcher,
# check-cloudbuild-substitutions, the deploy-status read-failure classification,
# audit-trust-cards) exists only here, and the next engagement forks from a
# template that has none of them.
#
#   platform change -> belongs upstream
#   AIPLA change    -> belongs here
#
# WHY PER-PATH AND NOT CHERRY-PICK: a real commit routinely straddles both tiers
# (a guard in a shared script plus the KU-specific prompt it was found in is ONE
# fix in TWO repos). Cherry-picking drags customer content upstream. This copies
# only the paths that survive classification, so a mixed commit splits correctly
# and KU content cannot ride along by construction. It is also the only option
# that works at all here: the two histories share no ancestor, so there is no
# commit to cherry-pick ONTO.
#
# UPSTREAM IS platform-source, NOT ai-protocol-platform. The public template is
# regenerated by force-pushing a fresh single-commit history, so a PR against it
# is destroyed by the next refresh. See .template-fork-target.
#
# Dry run by default.
#
# Usage:
#   scripts/port-up.sh                       # plan for unpushed commits
#   scripts/port-up.sh --all                 # plan for the full reconcile
#   scripts/port-up.sh <range>               # plan for an explicit git range
#   scripts/port-up.sh <range> GO=1          # ...and push the branch + open a PR
#
# Env:
#   GO=1              actually push and open the PR (otherwise: plan only)
#   PATHS=<file>      port exactly these paths (one per line), skipping
#                     derivation — the curated path, and the one to prefer for
#                     a first port: review bucket A by eye, keep what is
#                     genuinely platform code, feed the list back in
#   INCLUDE_NEW=1     also offer bucket C (files absent upstream)
#   BRANCH=<name>     branch name on the upstream repo
#   UPSTREAM=<url>    override the upstream remote URL

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

RANGE="${1:-}"
[ "$RANGE" = "GO=1" ] && RANGE=""
GO="${GO:-0}"
[ "${2:-}" = "GO=1" ] && GO=1

UPSTREAM_URL="${UPSTREAM:-$(sed -n 's/^UPSTREAM_REPO=//p' .template-fork-target 2>/dev/null | head -1)}"
UPSTREAM_URL="${UPSTREAM_URL:-$(git remote get-url upstream 2>/dev/null || true)}"
if [ -z "$UPSTREAM_URL" ]; then
  echo "No upstream. Set UPSTREAM_REPO in .template-fork-target or add an 'upstream' remote." >&2
  exit 2
fi

log() { echo "[port-up] $*"; }

log "range:    ${RANGE:-<unpushed commits>}"
log "upstream: $UPSTREAM_URL"

# Single source of truth for "is this template content" — see
# check-upstream-routing.sh. Never re-derive it here.
if [ -n "${PATHS:-}" ]; then
  [ -f "$PATHS" ] || { echo "PATHS file not found: $PATHS" >&2; exit 2; }
  log "using curated path list: $PATHS"
  PATH_LIST="$(sed 's/#.*//' "$PATHS" | sed '/^[[:space:]]*$/d')"
else
  log "deriving template paths …"
  PATH_LIST="$(PATHS_ONLY=1 INCLUDE_NEW="${INCLUDE_NEW:-0}" \
    bash scripts/check-upstream-routing.sh ${RANGE:+"$RANGE"})"
fi

if [ -z "$PATH_LIST" ]; then
  log "Nothing to port — every changed path is AIPLA-owned."
  exit 0
fi

COUNT="$(printf '%s\n' "$PATH_LIST" | sed '/^$/d' | wc -l | tr -d ' ')"
log "$COUNT path(s) to port:"
printf '%s\n' "$PATH_LIST" | sed 's/^/    /'

# Only paths that still EXIST here can be checked out. A path deleted in this
# repo needs a deliberate upstream deletion, which is a different review
# conversation — flag it rather than silently skipping.
MISSING=""
while IFS= read -r f; do
  [ -n "$f" ] || continue
  [ -e "$f" ] || MISSING="${MISSING}${f}"$'\n'
done <<< "$PATH_LIST"
if [ -n "$MISSING" ]; then
  echo
  log "NOTE: these were DELETED here and are not ported (deleting upstream is a"
  log "      separate, deliberate decision):"
  printf '%s' "$MISSING" | sed 's/^/    /'
fi

SHA="$(git rev-parse --short HEAD)"
BRANCH_NAME="${BRANCH:-port-up-aipla-$SHA}"

if [ "$GO" != 1 ]; then
  echo
  log "DRY RUN — nothing pushed. Would:"
  log "  1. clone $UPSTREAM_URL"
  log "  2. branch $BRANCH_NAME"
  log "  3. copy the $COUNT path(s) above from $(git branch --show-current) @ $SHA"
  log "  4. run the upstream backend suite (no AIPLA content present)"
  log "  5. push + open a PR"
  echo
  log "Re-run with GO=1 to execute."
  log "Prefer a curated first port: save the list, prune it, then"
  log "  PATHS=/path/to/list scripts/port-up.sh '' GO=1"
  exit 0
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

log "cloning upstream …"
git clone --quiet "$UPSTREAM_URL" "$WORK/up"
cd "$WORK/up"
git checkout -q -b "$BRANCH_NAME"
git remote add downstream "$REPO_ROOT"
git fetch -q downstream "$(cd "$REPO_ROOT" && git branch --show-current)"

log "copying paths …"
# xargs -0 so paths with spaces survive; -- so a leading-dash path is not a flag.
printf '%s' "$PATH_LIST" | sed '/^$/d' | tr '\n' '\0' \
  | xargs -0 git checkout FETCH_HEAD --

if git diff --cached --quiet; then
  log "Upstream already matches — nothing to port."
  exit 0
fi
git diff --cached --stat | tail -8

# The gate that matters: these must pass WITHOUT this deployment's skills,
# fixtures or branding present. A pass here is what proves the change is
# genuinely platform code and not quietly dependent on AIPLA content.
if [ -d backend ]; then
  log "running the upstream backend suite (no AIPLA content present) …"
  if ! ( cd backend && uv run pytest tests/ -m "not slow and not integration" -q 2>&1 | tail -5 ); then
    log "UPSTREAM TESTS FAILED — not pushing. The change likely depends on"
    log "something this repo has and upstream does not."
    exit 3
  fi
fi

git commit -q -m "Port platform changes from AIPLA fork @ $SHA

Copied per-path (not cherry-picked) so mixed commits split correctly and
customer content cannot ride along. Paths derived by check-upstream-routing.sh,
which classifies against the upstream tree, this fork's base commit, and an
AIPLA-marker screen.

Verified: upstream backend suite passes without AIPLA content present."

log "pushing $BRANCH_NAME …"
git push -q -u origin "$BRANCH_NAME"

if command -v gh >/dev/null 2>&1; then
  gh pr create --fill --head "$BRANCH_NAME" 2>&1 | tail -2 || \
    log "PR creation failed — branch is pushed, open it by hand."
else
  log "gh not found — branch pushed, open the PR by hand."
fi
