// GENERATED by scripts/generate-avatar-manifest.mjs — do not edit by hand.
// Add an avatar by dropping the image into frontend/public/personas/ and
// running `make avatars`. CI (`make check-avatars`) fails if the two drift.
//
// The set is CHOSEN from, never uploaded to (TUTOR-2 M4): no user-generated
// student-facing imagery, so no moderation policy is needed.

export interface AvatarChoice {
  /** Public path, exactly as a persona's `avatar` field stores it. */
  path: string;
  label: string;
}

export const AVATAR_CHOICES: AvatarChoice[] = [
  {
    "path": "/personas/amina.webp",
    "label": "Amina"
  },
  {
    "path": "/personas/astrid.webp",
    "label": "Astrid"
  },
  {
    "path": "/personas/frida.webp",
    "label": "Frida"
  },
  {
    "path": "/personas/henrik.webp",
    "label": "Henrik"
  },
  {
    "path": "/personas/jonas.webp",
    "label": "Jonas"
  },
  {
    "path": "/personas/mikkel.webp",
    "label": "Mikkel"
  },
  {
    "path": "/personas/sofie.webp",
    "label": "Sofie"
  }
];

/** The set the backend validates against, so "chosen, not uploaded" is true at
 *  the store and not only in the UI. */
export const AVATAR_PATHS: string[] = AVATAR_CHOICES.map((a) => a.path);
